### ISSUE TITLE
Error using  *  Call to cgemm in CUBLAS failed with error status: CUBLAS_STATUS_EXECUTION_FAILED.

### ISSUE THREAD

**Issue by kienprojects** [bigponglee/SL-SP-MRF#1]
I got this error while i try to run the main.m file

**Comment by bigponglee** [comment]
Hello,

This error could be caused by a variety of factors. To better identify the issue, please provide more detailed information such as the calculations you're performing, hardware and software being used, etc.

In the meantime, I recommend using the latest version of Matlab (2020 or later) and Windows 10 (or 11) operating system to run the program in an updated environment and see if the issue still persists.

Hope this helps!

**Comment by kienprojects** [comment]
Thank you for your response. Sir, while I try to run this repo, i got 3 error as below picture 
![image](https://user-images.githubusercontent.com/116629032/232690986-d7723aa2-5bc3-4f0b-a3b8-8d1e448dfa7b.png)
Im using Windows 11 Workstation with intel Core i7 10700k and RTX 3090, nvida-smi 12.0 with R2019a MATLAB. Could you help me debug this code ? Thank you so much

**Comment by bigponglee** [comment]
Hi again,

Based on the error message you mentioned earlier (CUBLAS_STATUS_EXECUTION_FAILED), it is possible that the error is related to the NVIDIA CUDA library. Deleting all the "gpuArray" statements in the code and using only the CPU may be a good starting point for debugging. (ps: this may be easy to solve the problem but also lead to increased running time)

However, if you were relying on the GPU acceleration feature, using only the CPU may not provide optimal performance. 
You can try Googling the specific error message to see if there are other solutions recommended by the community, such as update or reinstall the necessary CUDA-related libraries and drivers, which may resolve the issue.

Hope this helps!

**Comment by kienprojects** [comment]
Thank you so much for your cmt, could you provide the version of cuda, ver('cublas').. etc  used in your project so that i can upgrade/ downgrade my own. I appreciate that

**Comment by bigponglee** [comment]
Hello,

While my experience with using MATLAB with GPUs is somewhat limited, I believe the issue you are facing might be related to using a GPU to accelerate MATLAB through CUDA. It should be noted that MATLAB generally doesn't require a separate installation of CUDA for GPU acceleration. Instead, MATLAB typically relies on its built-in parallel computing toolbox to facilitate GPU acceleration. That said, our separate installation of CUDA for deep learning may not be relevant to this question.

In my personal experience, I've had no trouble running recent versions of MATLAB on both a desktop machine (MATLAB 2022 on Windows 11) and a server (Ubuntu and MATLAB 2020). Nonetheless, it's worth mentioning that our code has always run efficiently on CPUs as well. Therefore, I recommend running the code on the CPU first to confirm that the code works fine on your device. Then you can retrieve to solve the above problem.

I hope these tips help you in resolving the issue at hand. Please let me know if you have any further questions, and I'll do my best to assist you.

**Comment by kienprojects** [comment]
Thank you so much for your response. I appreciate that. I ll try to run it by CPU
